const API_ROUTES: Record<string, Record<string, string>> = {
  AUTH: {
    REGISTER_SEND_OTP: "/auth/register/send-otp",
    REGISTER_PENDING: "/auth/register/pending",
    REGISTER_RESEND_OTP: "/auth/register/resend-otp",
    REGISTER_VERIFY: "/auth/register/verify",
    ME: "/auth/me",
    HEARTBEAT: "/auth/heartbeat",
    EMAIL_INITIATE: "/auth/me/email/initiate",
    EMAIL_CONFIRM: "/auth/me/email/confirm",
    EMAIL_REQUEST_RECIPIENTS: "/auth/me/email/request-recipients",
    EMAIL_REQUEST: "/auth/me/email/request",
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    RESET_PASSWORD_VALIDATE: "/auth/reset-password/validate",
    INVITE_VALIDATE: "/auth/invites/validate",
    INVITE_ACCEPT: "/auth/invites/accept",
  },
  ADMIN: {
    ORGANIZATIONS: "/admin/organizations",
    ORGANIZATION_STATS: "/admin/organizations/stats",
    SUBSCRIPTIONS: "/admin/subscriptions",
    SUBSCRIPTION_STATS: "/admin/subscriptions/stats",
    SUBSCRIPTION_PLAN_DISTRIBUTION: "/admin/subscriptions/plan-distribution",
  },
  ORGANIZATIONS: {
    ME: "/organizations/me",
    ABOUT: "/organizations/me/about",
    MEMBERS: "/organizations/me/members",
  },
  ACTIVITY: {
    LIST: "/activity",
    FEED: "/activity/feed",
  },
  TEAMS: {
    MEMBERS: "/teams/members",
    STATS: "/teams/stats",
    INVITES: "/teams/invites",
    RESEND_PENDING: "/teams/invites/resend-pending",
  },
  PROJECTS: {
    LIST: "/projects",
    ASSIGNABLE_MEMBERS: "/projects/assignable-members",
  },
  CALENDAR: {
    EVENTS: "/calendar/events",
    PROJECTS: "/calendar/projects",
  },
  TASKS: {
    LIST: "/tasks",
    MY: "/tasks/my",
    DASHBOARD: "/tasks/dashboard",
    REPORTS: "/tasks/reports",
    BOARDS: "/tasks/boards",
  },
  BILLING: {
    CATALOG: "/billing/catalog",
    SUBSCRIPTION: "/billing/subscription",
    CHECKOUT: "/billing/checkout",
    CHECKOUT_CONFIRM: "/billing/checkout/confirm",
    SELECT_PLAN: "/billing/select-plan",
    CANCEL: "/billing/cancel",
    CHANGE_PLAN: "/billing/change-plan",
    REFUND: "/billing/refund",
    INVOICES: "/billing/invoices",
  },
};

export default API_ROUTES;
