const API_ROUTES: Record<string, Record<string, string>> = {
  AUTH: {
    REGISTER_SEND_OTP: "/auth/register/send-otp",
    REGISTER_PENDING: "/auth/register/pending",
    REGISTER_RESEND_OTP: "/auth/register/resend-otp",
    REGISTER_VERIFY: "/auth/register/verify",
    ME: "/auth/me",
    PROFILE: "/auth/me/profile",
    PASSWORD: "/auth/me/password",
    UI_THEME: "/auth/me/ui-theme",
    EMAIL_INITIATE: "/auth/me/email/initiate",
    EMAIL_CONFIRM: "/auth/me/email/confirm",
    EMAIL_REQUEST_RECIPIENTS: "/auth/me/email/request-recipients",
    EMAIL_REQUEST: "/auth/me/email/request",
    LOGIN: "/auth/login",
    REFRESH: "/auth/refresh",
    LOGOUT: "/auth/logout",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    RESET_PASSWORD_VALIDATE: "/auth/reset-password/validate",
    INVITE_VALIDATE: "/auth/invites/validate",
    INVITE_ACCEPT: "/auth/invites/accept",
    TWO_FACTOR_VERIFY: "/auth/2fa/verify",
    TWO_FACTOR_STATUS: "/auth/2fa/status",
    TWO_FACTOR_SETUP: "/auth/2fa/setup",
    TWO_FACTOR_ENABLE: "/auth/2fa/enable",
    TWO_FACTOR_DISABLE: "/auth/2fa/disable",
  },
  ADMIN: {
    ORGANIZATIONS: "/admin/organizations",
    ORGANIZATION_STATS: "/admin/organizations/stats",
    SUBSCRIPTIONS: "/admin/subscriptions",
    SUBSCRIPTION_STATS: "/admin/subscriptions/stats",
    SUBSCRIPTION_PLAN_DISTRIBUTION: "/admin/subscriptions/plan-distribution",
  },
  ORGANIZATIONS: {
    ME: "/organizations/me",
    ABOUT: "/organizations/me/about",
    MEMBERS: "/organizations/me/members",
    TWO_FACTOR_STATUS: "/organizations/me/2fa/status",
    TWO_FACTOR_SETUP: "/organizations/me/2fa/setup",
    TWO_FACTOR_CONFIRM: "/organizations/me/2fa/confirm",
    TWO_FACTOR_DISABLE: "/organizations/me/2fa/disable",
    TRANSFER_OWNERSHIP: "/organizations/me/transfer-ownership",
  },
  ACTIVITY: {
    LIST: "/activity",
    FEED: "/activity/feed",
  },
  TEAMS: {
    MEMBERS: "/teams/members",
    STATS: "/teams/stats",
    PRESENCE: "/teams/presence",
    INVITES: "/teams/invites",
    RESEND_PENDING: "/teams/invites/resend-pending",
  },
  PROJECTS: {
    LIST: "/projects",
    ASSIGNABLE_MEMBERS: "/projects/assignable-members",
    THEMES: "/projects/themes/list",
  },
  CALENDAR: {
    EVENTS: "/calendar/events",
    PROJECTS: "/calendar/projects",
  },
  TASKS: {
    LIST: "/tasks",
    MY: "/tasks/my",
    DASHBOARD: "/tasks/dashboard",
    REPORTS: "/tasks/reports",
    BOARDS: "/tasks/boards",
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    UNREAD_COUNT: "/notifications/unread-count",
    READ_ALL: "/notifications/read-all",
  },
  BILLING: {
    CATALOG: "/billing/catalog",
    SUBSCRIPTION: "/billing/subscription",
    USAGE: "/billing/usage",
    CHECKOUT: "/billing/checkout",
    CHECKOUT_CONFIRM: "/billing/checkout/confirm",
    SELECT_PLAN: "/billing/select-plan",
    CANCEL: "/billing/cancel",
    CHANGE_PLAN: "/billing/change-plan",
    REFUND: "/billing/refund",
    INVOICES: "/billing/invoices",
    PORTAL: "/billing/portal",
  },
  AI: {
    WORK_BREAKDOWN_GENERATE: "/ai/work-breakdown/generate",
    WORK_BREAKDOWN_APPLY: "/ai/work-breakdown/apply",
    PROJECT_SUMMARY_GENERATE: "/ai/project-summary/generate",
    PROJECT_DRAFT_GENERATE: "/ai/project-draft/generate",
    TASK_DRAFT_GENERATE: "/ai/task-draft/generate",
    ACTIVITY_DESCRIBE: "/ai/activity/describe",
    TASK_TIP_GENERATE: "/ai/task-tip/generate",
    MEMBERSHIP_IMPACT_GENERATE: "/ai/membership-impact/generate",
    CALENDAR_DRAFT_GENERATE: "/ai/calendar-draft/generate",
    ASK_WORKSPACE: "/ai/ask-workspace",
  },
};

export default API_ROUTES;
